window.atlasEntries = {

  tools: [
    { path: "/sectors/atlas/tools/age-calculator",             name: "Age Calculator" },
    { path: "/sectors/atlas/tools/aspect-ratio",               name: "Aspect Ratio" },
    { path: "/sectors/atlas/tools/base64",                     name: "Base64" },
    { path: "/sectors/atlas/tools/bill-splitter",              name: "Bill Splitter" },
    { path: "/sectors/atlas/tools/binary-translator",          name: "Binary Translator" },
    { path: "/sectors/atlas/tools/bmi-calculator",             name: "BMI Calculator" },
    { path: "/sectors/atlas/tools/budget-planner",             name: "Budget Planner" },
    { path: "/sectors/atlas/tools/caesar-cipher",              name: "Caesar Cipher" },
    { path: "/sectors/atlas/tools/calorie-calculator",         name: "Calorie Calculator" },
    { path: "/sectors/atlas/tools/case-converter",             name: "Case Converter" },
    { path: "/sectors/atlas/tools/character-counter",          name: "Character Counter" },
    { path: "/sectors/atlas/tools/color-contrast",             name: "Color Contrast" },
    { path: "/sectors/atlas/tools/color-palette",              name: "Color Palette" },
    { path: "/sectors/atlas/tools/color-picker",               name: "Color Picker" },
    { path: "/sectors/atlas/tools/compound-interest-calculator", name: "Compound Interest Calculator" },
    { path: "/sectors/atlas/tools/countdown-timer",            name: "Countdown Timer" },
    { path: "/sectors/atlas/tools/date-difference",            name: "Date Difference" },
    { path: "/sectors/atlas/tools/decision-spinner",           name: "Decision Spinner" },
    { path: "/sectors/atlas/tools/dice-roller",                name: "Dice Roller" },
    { path: "/sectors/atlas/tools/epoch-converter",            name: "Epoch Converter" },
    { path: "/sectors/atlas/tools/flashcards",                 name: "Flashcards" },
    { path: "/sectors/atlas/tools/gpa-calculator",             name: "GPA Calculator" },
    { path: "/sectors/atlas/tools/grade-calculator",           name: "Grade Calculator" },
    { path: "/sectors/atlas/tools/gradient-generator",         name: "Gradient Generator" },
    { path: "/sectors/atlas/tools/json-formatter",             name: "JSON Formatter" },
    { path: "/sectors/atlas/tools/loan-calculator",            name: "Loan Calculator" },
    { path: "/sectors/atlas/tools/lorem-ipsum",                name: "Lorem Ipsum" },
    { path: "/sectors/atlas/tools/markdown-previewer",         name: "Markdown Previewer" },
    { path: "/sectors/atlas/tools/metronome",                  name: "Metronome" },
    { path: "/sectors/atlas/tools/mortgage-calculator",        name: "Mortgage Calculator" },
    { path: "/sectors/atlas/tools/name-generator",             name: "Name Generator" },
    { path: "/sectors/atlas/tools/number-base-converter",      name: "Number Base Converter" },
    { path: "/sectors/atlas/tools/password-generator",         name: "Password Generator" },
    { path: "/sectors/atlas/tools/password-strength",          name: "Password Strength" },
    { path: "/sectors/atlas/tools/percentage-calculator",      name: "Percentage Calculator" },
    { path: "/sectors/atlas/tools/pomodoro-timer",             name: "Pomodoro Timer" },
    { path: "/sectors/atlas/tools/qr-code-generator",          name: "QR Code Generator" },
    { path: "/sectors/atlas/tools/quote-generator",            name: "Quote Generator" },
    { path: "/sectors/atlas/tools/random-number",              name: "Random Number" },
    { path: "/sectors/atlas/tools/reading-time",               name: "Reading Time" },
    { path: "/sectors/atlas/tools/regex-tester",               name: "Regex Tester" },
    { path: "/sectors/atlas/tools/roman-numerals",             name: "Roman Numerals" },
    { path: "/sectors/atlas/tools/salary-converter",           name: "Salary Converter" },
    { path: "/sectors/atlas/tools/savings-goal",               name: "Savings Goal" },
    { path: "/sectors/atlas/tools/scientific-calculator",      name: "Scientific Calculator" },
    { path: "/sectors/atlas/tools/shuffle-list",               name: "Shuffle List" },
    { path: "/sectors/atlas/tools/speed-calculator",           name: "Speed Calculator" },
    { path: "/sectors/atlas/tools/stopwatch",                  name: "Stopwatch" },
    { path: "/sectors/atlas/tools/text-diff",                  name: "Text Diff" },
    { path: "/sectors/atlas/tools/times-tables",               name: "Times Tables" },
    { path: "/sectors/atlas/tools/timezone-converter",         name: "Timezone Converter" },
    { path: "/sectors/atlas/tools/tip-calculator",             name: "Tip Calculator" },
    { path: "/sectors/atlas/tools/unit-converter",             name: "Unit Converter" },
    { path: "/sectors/atlas/tools/url-encoder",                name: "URL Encoder" },
    { path: "/sectors/atlas/tools/word-counter",               name: "Word Counter" }
  ],

  games: [
    { path: "/sectors/atlas/games/2048",                name: "2048" },
    { path: "/sectors/atlas/games/atlas-runner",        name: "Atlas Runner" },
    { path: "/sectors/atlas/games/battleship",          name: "Battleship" },
    { path: "/sectors/atlas/games/blackjack",           name: "Blackjack" },
    { path: "/sectors/atlas/games/breakout",            name: "Breakout" },
    { path: "/sectors/atlas/games/chess-forge",         name: "Chess Forge" },
    { path: "/sectors/atlas/games/color-match",         name: "Color Match" },
    { path: "/sectors/atlas/games/connect-four",        name: "Connect Four" },
    { path: "/sectors/atlas/games/flood-fill",          name: "Flood Fill" },
    { path: "/sectors/atlas/games/hangman",             name: "Hangman" },
    { path: "/sectors/atlas/games/higher-or-lower",     name: "Higher or Lower" },
    { path: "/sectors/atlas/games/lights-out",          name: "Lights Out" },
    { path: "/sectors/atlas/games/math-blitz",          name: "Math Blitz" },
    { path: "/sectors/atlas/games/maze",                name: "Maze" },
    { path: "/sectors/atlas/games/memory-match",        name: "Memory Match" },
    { path: "/sectors/atlas/games/minesweeper",         name: "Minesweeper" },
    { path: "/sectors/atlas/games/number-memory",       name: "Number Memory" },
    { path: "/sectors/atlas/games/pong",                name: "Pong" },
    { path: "/sectors/atlas/games/reaction-time",       name: "Reaction Time" },
    { path: "/sectors/atlas/games/rock-paper-scissors", name: "Rock Paper Scissors" },
    { path: "/sectors/atlas/games/simon-says",          name: "Simon Says" },
    { path: "/sectors/atlas/games/sliding-puzzle",      name: "Sliding Puzzle" },
    { path: "/sectors/atlas/games/snake",               name: "Snake" },
    { path: "/sectors/atlas/games/stroop-test",         name: "Stroop Test" },
    { path: "/sectors/atlas/games/sudoku",              name: "Sudoku" },
    { path: "/sectors/atlas/games/tetris",              name: "Tetris" },
    { path: "/sectors/atlas/games/tic-tac-toe",         name: "Tic Tac Toe" },
    { path: "/sectors/atlas/games/tower-of-hanoi",      name: "Tower of Hanoi" },
    { path: "/sectors/atlas/games/trivia",              name: "Trivia" },
    { path: "/sectors/atlas/games/type-speed",          name: "Type Speed" },
    { path: "/sectors/atlas/games/typing-practice",     name: "Typing Practice" },
    { path: "/sectors/atlas/games/whack-a-mole",        name: "Whack a Mole" },
    { path: "/sectors/atlas/games/word-scramble",       name: "Word Scramble" },
    { path: "/sectors/atlas/games/wordle",              name: "Wordle" }
  ]

};
